import type { LanguageCourse } from "../types";

export const frenchCourse: LanguageCourse = {
  language: "french",
  flag: "🇫🇷",
  displayName: "French",
  lessons: [
    {
      id: "fr-greetings",
      title: "Greetings",
      description: "Learn how to greet people in French",
      words: [
        { word: "Bonjour", translation: "Hello / Good day", pronunciation: "bohn-ZHOOR", example: "Bonjour! Comment allez-vous?", exampleTranslation: "Hello! How are you?" },
        { word: "Au revoir", translation: "Goodbye", pronunciation: "oh ruh-VWAHR", example: "Au revoir! À bientôt.", exampleTranslation: "Goodbye! See you soon." },
        { word: "Merci", translation: "Thank you", pronunciation: "mehr-SEE", example: "Merci beaucoup!", exampleTranslation: "Thank you very much!" },
        { word: "S'il vous plaît", translation: "Please", pronunciation: "seel voo PLEH", example: "Un café, s'il vous plaît.", exampleTranslation: "A coffee, please." },
        { word: "Excusez-moi", translation: "Excuse me", pronunciation: "ex-koo-zay MWAH", example: "Excusez-moi, où est la gare?", exampleTranslation: "Excuse me, where is the station?" },
      ],
      quiz: [
        { question: "What does 'Bonjour' mean?", options: ["Goodbye", "Thank you", "Hello", "Please"], correctIndex: 2 },
        { question: "How do you say 'Thank you'?", options: ["Bonjour", "Au revoir", "Merci", "Excusez-moi"], correctIndex: 2 },
        { question: "What does 'Au revoir' mean?", options: ["Hello", "Goodbye", "Please", "Excuse me"], correctIndex: 1 },
        { question: "Listen and choose the meaning", options: ["Thank you", "Hello", "Goodbye", "Excuse me"], correctIndex: 3, type: "listening", listenWord: "Excusez-moi" },
        { question: "Listen and choose the meaning", options: ["Excuse me", "Thank you", "Please", "Hello"], correctIndex: 2, type: "listening", listenWord: "S'il vous plaît" },
      ],
    },
    {
      id: "fr-numbers",
      title: "Numbers 1–10",
      description: "Count from one to ten in French",
      words: [
        { word: "Un", translation: "One", pronunciation: "uhn" },
        { word: "Deux", translation: "Two", pronunciation: "duh" },
        { word: "Trois", translation: "Three", pronunciation: "twah" },
        { word: "Quatre", translation: "Four", pronunciation: "KAH-truh" },
        { word: "Cinq", translation: "Five", pronunciation: "sank" },
        { word: "Six", translation: "Six", pronunciation: "sees" },
        { word: "Sept", translation: "Seven", pronunciation: "set" },
        { word: "Huit", translation: "Eight", pronunciation: "weet" },
        { word: "Neuf", translation: "Nine", pronunciation: "nuhf" },
        { word: "Dix", translation: "Ten", pronunciation: "dees" },
      ],
      quiz: [
        { question: "What does 'Trois' mean?", options: ["Two", "Four", "Three", "Five"], correctIndex: 2 },
        { question: "How do you say 'Seven'?", options: ["Six", "Sept", "Huit", "Neuf"], correctIndex: 1 },
        { question: "What does 'Dix' mean?", options: ["Eight", "Nine", "Six", "Ten"], correctIndex: 3 },
        { question: "Listen and choose the meaning", options: ["Four", "Five", "Six", "Three"], correctIndex: 1, type: "listening", listenWord: "Cinq" },
        { question: "Listen and choose the meaning", options: ["Two", "Three", "One", "Four"], correctIndex: 2, type: "listening", listenWord: "Un" },
      ],
    },
    {
      id: "fr-food",
      title: "Food & Drink",
      description: "Learn common food and drink words in French",
      words: [
        { word: "Le pain", translation: "Bread", pronunciation: "luh pan", example: "Je voudrais du pain.", exampleTranslation: "I would like some bread." },
        { word: "L'eau", translation: "Water", pronunciation: "loh", example: "Un verre d'eau, s'il vous plaît.", exampleTranslation: "A glass of water, please." },
        { word: "Le café", translation: "Coffee", pronunciation: "luh kah-FAY", example: "Je prends un café.", exampleTranslation: "I'll have a coffee." },
        { word: "Le fromage", translation: "Cheese", pronunciation: "luh froh-MAHZH", example: "Le fromage est délicieux.", exampleTranslation: "The cheese is delicious." },
        { word: "Le vin", translation: "Wine", pronunciation: "luh van", example: "Un verre de vin rouge, s'il vous plaît.", exampleTranslation: "A glass of red wine, please." },
        { word: "La pomme", translation: "Apple", pronunciation: "lah pom", example: "Je mange une pomme.", exampleTranslation: "I am eating an apple." },
      ],
      quiz: [
        { question: "What does 'Le pain' mean?", options: ["Coffee", "Water", "Bread", "Wine"], correctIndex: 2 },
        { question: "How do you say 'Water'?", options: ["Le vin", "Le café", "Le fromage", "L'eau"], correctIndex: 3 },
        { question: "What does 'Le fromage' mean?", options: ["Bread", "Cheese", "Apple", "Wine"], correctIndex: 1 },
        { question: "Listen and choose the meaning", options: ["Wine", "Cheese", "Water", "Apple"], correctIndex: 3, type: "listening", listenWord: "La pomme" },
        { question: "Listen and choose the meaning", options: ["Apple", "Coffee", "Bread", "Wine"], correctIndex: 3, type: "listening", listenWord: "Le vin" },
      ],
    },
    {
      id: "fr-family",
      title: "Family",
      description: "Learn family member words in French",
      words: [
        { word: "La mère", translation: "Mother", pronunciation: "lah mehr", example: "Ma mère est médecin.", exampleTranslation: "My mother is a doctor." },
        { word: "Le père", translation: "Father", pronunciation: "luh pehr", example: "Mon père travaille beaucoup.", exampleTranslation: "My father works a lot." },
        { word: "Le frère", translation: "Brother", pronunciation: "luh frehr", example: "Mon frère est plus grand que moi.", exampleTranslation: "My brother is taller than me." },
        { word: "La sœur", translation: "Sister", pronunciation: "lah suhr", example: "Ma sœur est très intelligente.", exampleTranslation: "My sister is very intelligent." },
        { word: "Le grand-père", translation: "Grandfather", pronunciation: "luh grahn-pehr", example: "Mon grand-père a quatre-vingts ans.", exampleTranslation: "My grandfather is eighty years old." },
        { word: "La grand-mère", translation: "Grandmother", pronunciation: "lah grahn-mehr", example: "La grand-mère fait de bons gâteaux.", exampleTranslation: "Grandmother makes good cakes." },
      ],
      quiz: [
        { question: "What does 'La mère' mean?", options: ["Father", "Sister", "Mother", "Brother"], correctIndex: 2 },
        { question: "How do you say 'Brother'?", options: ["La sœur", "Le père", "Le frère", "Le grand-père"], correctIndex: 2 },
        { question: "What does 'Le grand-père' mean?", options: ["Grandmother", "Father", "Grandfather", "Uncle"], correctIndex: 2 },
        { question: "Listen and choose the meaning", options: ["Sister", "Mother", "Grandfather", "Grandmother"], correctIndex: 3, type: "listening", listenWord: "La grand-mère" },
        { question: "Listen and choose the meaning", options: ["Brother", "Father", "Sister", "Mother"], correctIndex: 1, type: "listening", listenWord: "Le père" },
      ],
    },
    {
      id: "fr-colors",
      title: "Colors",
      description: "Learn the basic colors in French",
      words: [
        { word: "Rouge", translation: "Red", pronunciation: "roozh", example: "La rose est rouge.", exampleTranslation: "The rose is red." },
        { word: "Bleu", translation: "Blue", pronunciation: "bluh", example: "Le ciel est bleu.", exampleTranslation: "The sky is blue." },
        { word: "Vert", translation: "Green", pronunciation: "vehr", example: "L'herbe est verte.", exampleTranslation: "The grass is green." },
        { word: "Jaune", translation: "Yellow", pronunciation: "zhohn", example: "Le soleil est jaune.", exampleTranslation: "The sun is yellow." },
        { word: "Noir", translation: "Black", pronunciation: "nwahr", example: "Le chat est noir.", exampleTranslation: "The cat is black." },
        { word: "Blanc", translation: "White", pronunciation: "blahn", example: "La neige est blanche.", exampleTranslation: "The snow is white." },
      ],
      quiz: [
        { question: "What does 'Rouge' mean?", options: ["Blue", "Green", "Red", "Yellow"], correctIndex: 2 },
        { question: "How do you say 'Blue'?", options: ["Vert", "Rouge", "Bleu", "Noir"], correctIndex: 2 },
        { question: "What does 'Jaune' mean?", options: ["Green", "Yellow", "White", "Black"], correctIndex: 1 },
        { question: "Listen and choose the meaning", options: ["Black", "White", "Red", "Blue"], correctIndex: 1, type: "listening", listenWord: "Blanc" },
        { question: "Listen and choose the meaning", options: ["Blue", "Yellow", "Green", "Red"], correctIndex: 2, type: "listening", listenWord: "Vert" },
      ],
    },
    {
      id: "fr-travel",
      title: "Travel",
      description: "Essential phrases for travelling in French",
      words: [
        { word: "L'aéroport", translation: "Airport", pronunciation: "lah-eh-roh-POR", example: "L'aéroport est loin.", exampleTranslation: "The airport is far." },
        { word: "L'hôtel", translation: "Hotel", pronunciation: "loh-TEHL", example: "J'ai réservé une chambre à l'hôtel.", exampleTranslation: "I booked a room at the hotel." },
        { word: "Le restaurant", translation: "Restaurant", pronunciation: "luh res-toh-RAHN", example: "Le restaurant ouvre à huit heures.", exampleTranslation: "The restaurant opens at eight." },
        { word: "L'aide", translation: "Help", pronunciation: "lehd", example: "J'ai besoin d'aide!", exampleTranslation: "I need help!" },
        { word: "Les toilettes", translation: "Bathroom", pronunciation: "leh twah-LET", example: "Où sont les toilettes?", exampleTranslation: "Where is the bathroom?" },
        { word: "Le billet", translation: "Ticket", pronunciation: "luh bee-YEH", example: "J'ai besoin d'un billet de train.", exampleTranslation: "I need a train ticket." },
      ],
      quiz: [
        { question: "What does 'L'aéroport' mean?", options: ["Hotel", "Restaurant", "Airport", "Station"], correctIndex: 2 },
        { question: "How do you say 'Help'?", options: ["Les toilettes", "Le billet", "L'hôtel", "L'aide"], correctIndex: 3 },
        { question: "What does 'Les toilettes' mean?", options: ["Ticket", "Airport", "Restaurant", "Bathroom"], correctIndex: 3 },
        { question: "Listen and choose the meaning", options: ["Airport", "Restaurant", "Bathroom", "Hotel"], correctIndex: 3, type: "listening", listenWord: "L'hôtel" },
        { question: "Listen and choose the meaning", options: ["Help", "Bathroom", "Ticket", "Airport"], correctIndex: 2, type: "listening", listenWord: "Le billet" },
      ],
    },
  ],
};
