import type { LanguageCourse } from "../types";

export const japaneseCourse: LanguageCourse = {
  language: "japanese",
  flag: "🇯🇵",
  displayName: "Japanese",
  lessons: [
    {
      id: "ja-greetings",
      title: "Greetings",
      description: "Learn how to greet people in Japanese",
      words: [
        { word: "こんにちは", translation: "Hello", pronunciation: "Konnichiwa", example: "こんにちは！お元気ですか？", exampleTranslation: "Hello! How are you?" },
        { word: "おはようございます", translation: "Good morning", pronunciation: "Ohayou gozaimasu", example: "おはようございます、田中さん。", exampleTranslation: "Good morning, Tanaka-san." },
        { word: "こんばんは", translation: "Good evening", pronunciation: "Konbanwa", example: "こんばんは！今日はどうでしたか？", exampleTranslation: "Good evening! How was today?" },
        { word: "さようなら", translation: "Goodbye", pronunciation: "Sayounara", example: "さようなら、またね。", exampleTranslation: "Goodbye, see you again." },
        { word: "ありがとう", translation: "Thank you", pronunciation: "Arigatou", example: "ありがとう、助かりました。", exampleTranslation: "Thank you, that was helpful." },
      ],
      quiz: [
        { question: "What does 'こんにちは' mean?", options: ["Goodbye", "Good morning", "Hello", "Thank you"], correctIndex: 2 },
        { question: "How do you say 'Good morning'?", options: ["こんばんは", "さようなら", "おはようございます", "ありがとう"], correctIndex: 2 },
        { question: "What does 'さようなら' mean?", options: ["Hello", "Goodbye", "Good evening", "Please"], correctIndex: 1 },
        { question: "Listen and choose the meaning", options: ["Good morning", "Hello", "Thank you", "Good evening"], correctIndex: 3, type: "listening", listenWord: "こんばんは" },
        { question: "Listen and choose the meaning", options: ["Goodbye", "Good evening", "Hello", "Good morning"], correctIndex: 3, type: "listening", listenWord: "ありがとう" },
      ],
    },
    {
      id: "ja-numbers",
      title: "Numbers 1–10",
      description: "Count from one to ten in Japanese",
      words: [
        { word: "一", translation: "One", pronunciation: "Ichi" },
        { word: "二", translation: "Two", pronunciation: "Ni" },
        { word: "三", translation: "Three", pronunciation: "San" },
        { word: "四", translation: "Four", pronunciation: "Shi / Yon" },
        { word: "五", translation: "Five", pronunciation: "Go" },
        { word: "六", translation: "Six", pronunciation: "Roku" },
        { word: "七", translation: "Seven", pronunciation: "Shichi / Nana" },
        { word: "八", translation: "Eight", pronunciation: "Hachi" },
        { word: "九", translation: "Nine", pronunciation: "Ku / Kyuu" },
        { word: "十", translation: "Ten", pronunciation: "Juu" },
      ],
      quiz: [
        { question: "What does '三' mean?", options: ["Two", "Four", "Three", "Five"], correctIndex: 2 },
        { question: "How do you say 'Seven'?", options: ["六 (Roku)", "七 (Shichi)", "八 (Hachi)", "九 (Ku)"], correctIndex: 1 },
        { question: "What does '十' mean?", options: ["Eight", "Nine", "Six", "Ten"], correctIndex: 3 },
        { question: "Listen and choose the meaning", options: ["Four", "Five", "Six", "Three"], correctIndex: 1, type: "listening", listenWord: "五" },
        { question: "Listen and choose the meaning", options: ["Two", "Three", "One", "Four"], correctIndex: 2, type: "listening", listenWord: "一" },
      ],
    },
    {
      id: "ja-food",
      title: "Food & Drink",
      description: "Learn common food and drink words in Japanese",
      words: [
        { word: "ごはん", translation: "Rice / Meal", pronunciation: "Gohan", example: "ごはんを食べましょう。", exampleTranslation: "Let's eat a meal." },
        { word: "みず", translation: "Water", pronunciation: "Mizu", example: "みずをください。", exampleTranslation: "Please give me water." },
        { word: "おちゃ", translation: "Tea", pronunciation: "Ocha", example: "おちゃが好きです。", exampleTranslation: "I like tea." },
        { word: "すし", translation: "Sushi", pronunciation: "Sushi", example: "すしはおいしいです。", exampleTranslation: "Sushi is delicious." },
        { word: "ラーメン", translation: "Ramen", pronunciation: "Raamen", example: "ラーメンを食べたいです。", exampleTranslation: "I want to eat ramen." },
        { word: "たまご", translation: "Egg", pronunciation: "Tamago", example: "たまごが二つあります。", exampleTranslation: "There are two eggs." },
      ],
      quiz: [
        { question: "What does 'ごはん' mean?", options: ["Tea", "Water", "Rice / Meal", "Egg"], correctIndex: 2 },
        { question: "How do you say 'Water'?", options: ["おちゃ", "ごはん", "みず", "すし"], correctIndex: 2 },
        { question: "What does 'すし' mean?", options: ["Ramen", "Sushi", "Egg", "Tea"], correctIndex: 1 },
        { question: "Listen and choose the meaning", options: ["Sushi", "Water", "Rice", "Egg"], correctIndex: 3, type: "listening", listenWord: "たまご" },
        { question: "Listen and choose the meaning", options: ["Water", "Egg", "Tea", "Apple"], correctIndex: 2, type: "listening", listenWord: "おちゃ" },
      ],
    },
    {
      id: "ja-family",
      title: "Family",
      description: "Learn family member words in Japanese",
      words: [
        { word: "お母さん", translation: "Mother", pronunciation: "Okāsan", example: "お母さんは料理が上手です。", exampleTranslation: "My mother is good at cooking." },
        { word: "お父さん", translation: "Father", pronunciation: "Otōsan", example: "お父さんは会社で働いています。", exampleTranslation: "My father works at a company." },
        { word: "兄", translation: "Older brother", pronunciation: "Ani", example: "兄はとても背が高いです。", exampleTranslation: "My older brother is very tall." },
        { word: "姉", translation: "Older sister", pronunciation: "Ane", example: "姉は大学生です。", exampleTranslation: "My older sister is a university student." },
        { word: "弟", translation: "Younger brother", pronunciation: "Otōto", example: "弟はまだ小学生です。", exampleTranslation: "My younger brother is still in elementary school." },
        { word: "妹", translation: "Younger sister", pronunciation: "Imōto", example: "妹はピアノが弾けます。", exampleTranslation: "My younger sister can play the piano." },
      ],
      quiz: [
        { question: "What does 'お母さん' mean?", options: ["Father", "Sister", "Mother", "Brother"], correctIndex: 2 },
        { question: "How do you say 'Older brother'?", options: ["弟", "お父さん", "兄", "姉"], correctIndex: 2 },
        { question: "What does '妹' mean?", options: ["Older sister", "Mother", "Younger sister", "Father"], correctIndex: 2 },
        { question: "Listen and choose the meaning", options: ["Younger sister", "Mother", "Younger brother", "Older sister"], correctIndex: 3, type: "listening", listenWord: "姉" },
        { question: "Listen and choose the meaning", options: ["Mother", "Older brother", "Father", "Older sister"], correctIndex: 2, type: "listening", listenWord: "お父さん" },
      ],
    },
    {
      id: "ja-colors",
      title: "Colors",
      description: "Learn the basic colors in Japanese",
      words: [
        { word: "赤", translation: "Red", pronunciation: "Aka", example: "このリンゴは赤いです。", exampleTranslation: "This apple is red." },
        { word: "青", translation: "Blue", pronunciation: "Ao", example: "空は青いです。", exampleTranslation: "The sky is blue." },
        { word: "緑", translation: "Green", pronunciation: "Midori", example: "草は緑色です。", exampleTranslation: "The grass is green." },
        { word: "黄色", translation: "Yellow", pronunciation: "Kiiro", example: "バナナは黄色いです。", exampleTranslation: "Bananas are yellow." },
        { word: "黒", translation: "Black", pronunciation: "Kuro", example: "この猫は黒いです。", exampleTranslation: "This cat is black." },
        { word: "白", translation: "White", pronunciation: "Shiro", example: "雪は白いです。", exampleTranslation: "Snow is white." },
      ],
      quiz: [
        { question: "What does '赤' mean?", options: ["Blue", "Green", "Red", "Yellow"], correctIndex: 2 },
        { question: "How do you say 'Blue'?", options: ["緑", "赤", "青", "黒"], correctIndex: 2 },
        { question: "What does '黄色' mean?", options: ["Green", "Yellow", "White", "Black"], correctIndex: 1 },
        { question: "Listen and choose the meaning", options: ["Black", "White", "Red", "Blue"], correctIndex: 1, type: "listening", listenWord: "白" },
        { question: "Listen and choose the meaning", options: ["Blue", "Yellow", "Green", "Red"], correctIndex: 2, type: "listening", listenWord: "緑" },
      ],
    },
    {
      id: "ja-travel",
      title: "Travel",
      description: "Essential phrases for travelling in Japanese",
      words: [
        { word: "空港", translation: "Airport", pronunciation: "Kūkō", example: "空港はどこですか？", exampleTranslation: "Where is the airport?" },
        { word: "ホテル", translation: "Hotel", pronunciation: "Hoteru", example: "このホテルは快適です。", exampleTranslation: "This hotel is comfortable." },
        { word: "レストラン", translation: "Restaurant", pronunciation: "Resutoran", example: "レストランは何時に開きますか？", exampleTranslation: "What time does the restaurant open?" },
        { word: "助けて", translation: "Help!", pronunciation: "Tasukete", example: "助けて！", exampleTranslation: "Help!" },
        { word: "トイレ", translation: "Bathroom", pronunciation: "Toire", example: "トイレはどこですか？", exampleTranslation: "Where is the bathroom?" },
        { word: "切符", translation: "Ticket", pronunciation: "Kippu", example: "切符を一枚ください。", exampleTranslation: "One ticket, please." },
      ],
      quiz: [
        { question: "What does '空港' mean?", options: ["Hotel", "Restaurant", "Airport", "Station"], correctIndex: 2 },
        { question: "How do you say 'Help!'?", options: ["トイレ", "切符", "ホテル", "助けて"], correctIndex: 3 },
        { question: "What does 'トイレ' mean?", options: ["Ticket", "Airport", "Restaurant", "Bathroom"], correctIndex: 3 },
        { question: "Listen and choose the meaning", options: ["Airport", "Restaurant", "Bathroom", "Hotel"], correctIndex: 3, type: "listening", listenWord: "ホテル" },
        { question: "Listen and choose the meaning", options: ["Help", "Bathroom", "Ticket", "Airport"], correctIndex: 2, type: "listening", listenWord: "切符" },
      ],
    },
  ],
};
