import type { LanguageCourse } from "../types";

export const koreanCourse: LanguageCourse = {
  language: "korean",
  flag: "🇰🇷",
  displayName: "Korean",
  lessons: [
    {
      id: "ko-greetings",
      title: "Greetings",
      description: "Learn how to greet people in Korean",
      words: [
        { word: "안녕하세요", translation: "Hello", pronunciation: "Annyeonghaseyo", example: "안녕하세요! 만나서 반가워요.", exampleTranslation: "Hello! Nice to meet you." },
        { word: "안녕히 가세요", translation: "Goodbye (to someone leaving)", pronunciation: "Annyeonghi gaseyo", example: "안녕히 가세요, 내일 봬요.", exampleTranslation: "Goodbye, see you tomorrow." },
        { word: "감사합니다", translation: "Thank you", pronunciation: "Gamsahamnida", example: "도와줘서 감사합니다.", exampleTranslation: "Thank you for helping me." },
        { word: "죄송합니다", translation: "I'm sorry", pronunciation: "Joesonghamnida", example: "늦어서 죄송합니다.", exampleTranslation: "I'm sorry for being late." },
        { word: "괜찮아요", translation: "It's okay", pronunciation: "Gwaenchanayo", example: "괜찮아요, 걱정하지 마세요.", exampleTranslation: "It's okay, don't worry." },
      ],
      quiz: [
        { question: "What does '안녕하세요' mean?", options: ["Goodbye", "Thank you", "Hello", "I'm sorry"], correctIndex: 2 },
        { question: "How do you say 'Thank you'?", options: ["괜찮아요", "죄송합니다", "감사합니다", "안녕하세요"], correctIndex: 2 },
        { question: "What does '죄송합니다' mean?", options: ["Hello", "It's okay", "Thank you", "I'm sorry"], correctIndex: 3 },
        { question: "Listen and choose the meaning", options: ["Hello", "Thank you", "Goodbye", "I'm sorry"], correctIndex: 2, type: "listening", listenWord: "안녕히 가세요" },
        { question: "Listen and choose the meaning", options: ["Thank you", "I'm sorry", "Hello", "It's okay"], correctIndex: 3, type: "listening", listenWord: "괜찮아요" },
      ],
    },
    {
      id: "ko-numbers",
      title: "Numbers 1–10",
      description: "Count from one to ten in Korean",
      words: [
        { word: "일", translation: "One", pronunciation: "Il" },
        { word: "이", translation: "Two", pronunciation: "I" },
        { word: "삼", translation: "Three", pronunciation: "Sam" },
        { word: "사", translation: "Four", pronunciation: "Sa" },
        { word: "오", translation: "Five", pronunciation: "O" },
        { word: "육", translation: "Six", pronunciation: "Yuk" },
        { word: "칠", translation: "Seven", pronunciation: "Chil" },
        { word: "팔", translation: "Eight", pronunciation: "Pal" },
        { word: "구", translation: "Nine", pronunciation: "Gu" },
        { word: "십", translation: "Ten", pronunciation: "Sip" },
      ],
      quiz: [
        { question: "What does '삼' mean?", options: ["Two", "Four", "Three", "Five"], correctIndex: 2 },
        { question: "How do you say 'Seven'?", options: ["육 (Yuk)", "칠 (Chil)", "팔 (Pal)", "구 (Gu)"], correctIndex: 1 },
        { question: "What does '십' mean?", options: ["Eight", "Nine", "Six", "Ten"], correctIndex: 3 },
        { question: "Listen and choose the meaning", options: ["Four", "Five", "Six", "Three"], correctIndex: 1, type: "listening", listenWord: "오" },
        { question: "Listen and choose the meaning", options: ["Two", "Three", "One", "Four"], correctIndex: 2, type: "listening", listenWord: "일" },
      ],
    },
    {
      id: "ko-food",
      title: "Food & Drink",
      description: "Learn common food and drink words in Korean",
      words: [
        { word: "밥", translation: "Rice / Meal", pronunciation: "Bap", example: "밥 먹었어요?", exampleTranslation: "Have you eaten?" },
        { word: "물", translation: "Water", pronunciation: "Mul", example: "물 한 잔 주세요.", exampleTranslation: "Please give me a glass of water." },
        { word: "김치", translation: "Kimchi", pronunciation: "Kimchi", example: "김치가 맛있어요.", exampleTranslation: "The kimchi is delicious." },
        { word: "불고기", translation: "Bulgogi (grilled beef)", pronunciation: "Bulgogi", example: "불고기를 좋아해요.", exampleTranslation: "I like bulgogi." },
        { word: "커피", translation: "Coffee", pronunciation: "Keopi", example: "커피 한 잔 마실래요?", exampleTranslation: "Would you like a cup of coffee?" },
        { word: "사과", translation: "Apple", pronunciation: "Sagwa", example: "사과가 달아요.", exampleTranslation: "The apple is sweet." },
      ],
      quiz: [
        { question: "What does '밥' mean?", options: ["Coffee", "Water", "Rice / Meal", "Apple"], correctIndex: 2 },
        { question: "How do you say 'Water'?", options: ["커피", "밥", "물", "김치"], correctIndex: 2 },
        { question: "What does '김치' mean?", options: ["Bulgogi", "Kimchi", "Apple", "Coffee"], correctIndex: 1 },
        { question: "Listen and choose the meaning", options: ["Kimchi", "Water", "Rice", "Apple"], correctIndex: 3, type: "listening", listenWord: "사과" },
        { question: "Listen and choose the meaning", options: ["Water", "Kimchi", "Coffee", "Apple"], correctIndex: 2, type: "listening", listenWord: "커피" },
      ],
    },
    {
      id: "ko-family",
      title: "Family",
      description: "Learn family member words in Korean",
      words: [
        { word: "어머니", translation: "Mother", pronunciation: "Eomeoni", example: "어머니는 요리를 잘하세요.", exampleTranslation: "My mother is good at cooking." },
        { word: "아버지", translation: "Father", pronunciation: "Abeoji", example: "아버지는 회사에서 일하세요.", exampleTranslation: "My father works at a company." },
        { word: "오빠 / 형", translation: "Older brother", pronunciation: "Oppa / Hyeong", example: "오빠는 키가 커요.", exampleTranslation: "My older brother is tall." },
        { word: "언니 / 누나", translation: "Older sister", pronunciation: "Eonni / Nuna", example: "언니는 대학생이에요.", exampleTranslation: "My older sister is a university student." },
        { word: "남동생", translation: "Younger brother", pronunciation: "Namdongsaeng", example: "남동생은 초등학생이에요.", exampleTranslation: "My younger brother is in elementary school." },
        { word: "여동생", translation: "Younger sister", pronunciation: "Yeodongsaeng", example: "여동생은 피아노를 쳐요.", exampleTranslation: "My younger sister plays the piano." },
      ],
      quiz: [
        { question: "What does '어머니' mean?", options: ["Father", "Sister", "Mother", "Brother"], correctIndex: 2 },
        { question: "How do you say 'Older brother'?", options: ["남동생", "아버지", "오빠 / 형", "언니 / 누나"], correctIndex: 2 },
        { question: "What does '여동생' mean?", options: ["Older sister", "Mother", "Younger sister", "Father"], correctIndex: 2 },
        { question: "Listen and choose the meaning", options: ["Younger sister", "Mother", "Younger brother", "Older sister"], correctIndex: 3, type: "listening", listenWord: "언니 / 누나" },
        { question: "Listen and choose the meaning", options: ["Mother", "Older brother", "Father", "Older sister"], correctIndex: 2, type: "listening", listenWord: "아버지" },
      ],
    },
    {
      id: "ko-colors",
      title: "Colors",
      description: "Learn the basic colors in Korean",
      words: [
        { word: "빨간색", translation: "Red", pronunciation: "Ppalgansaek", example: "이 사과는 빨간색이에요.", exampleTranslation: "This apple is red." },
        { word: "파란색", translation: "Blue", pronunciation: "Paransaek", example: "하늘은 파란색이에요.", exampleTranslation: "The sky is blue." },
        { word: "초록색", translation: "Green", pronunciation: "Choroksaek", example: "풀은 초록색이에요.", exampleTranslation: "The grass is green." },
        { word: "노란색", translation: "Yellow", pronunciation: "Noransaek", example: "바나나는 노란색이에요.", exampleTranslation: "Bananas are yellow." },
        { word: "검은색", translation: "Black", pronunciation: "Geomeunsaek", example: "이 고양이는 검은색이에요.", exampleTranslation: "This cat is black." },
        { word: "흰색", translation: "White", pronunciation: "Huinsaek", example: "눈은 흰색이에요.", exampleTranslation: "Snow is white." },
      ],
      quiz: [
        { question: "What does '빨간색' mean?", options: ["Blue", "Green", "Red", "Yellow"], correctIndex: 2 },
        { question: "How do you say 'Blue'?", options: ["초록색", "빨간색", "파란색", "검은색"], correctIndex: 2 },
        { question: "What does '노란색' mean?", options: ["Green", "Yellow", "White", "Black"], correctIndex: 1 },
        { question: "Listen and choose the meaning", options: ["Black", "White", "Red", "Blue"], correctIndex: 1, type: "listening", listenWord: "흰색" },
        { question: "Listen and choose the meaning", options: ["Blue", "Yellow", "Green", "Red"], correctIndex: 2, type: "listening", listenWord: "초록색" },
      ],
    },
    {
      id: "ko-travel",
      title: "Travel",
      description: "Essential phrases for travelling in Korean",
      words: [
        { word: "공항", translation: "Airport", pronunciation: "Gonghang", example: "공항까지 어떻게 가요?", exampleTranslation: "How do I get to the airport?" },
        { word: "호텔", translation: "Hotel", pronunciation: "Hotel", example: "이 호텔은 편안해요.", exampleTranslation: "This hotel is comfortable." },
        { word: "식당", translation: "Restaurant", pronunciation: "Sikdang", example: "식당은 몇 시에 열어요?", exampleTranslation: "What time does the restaurant open?" },
        { word: "도와주세요", translation: "Please help me", pronunciation: "Dowajuseyo", example: "도와주세요!", exampleTranslation: "Please help me!" },
        { word: "화장실", translation: "Bathroom", pronunciation: "Hwajangsil", example: "화장실이 어디예요?", exampleTranslation: "Where is the bathroom?" },
        { word: "티켓", translation: "Ticket", pronunciation: "Tiket", example: "티켓 한 장 주세요.", exampleTranslation: "One ticket, please." },
      ],
      quiz: [
        { question: "What does '공항' mean?", options: ["Hotel", "Restaurant", "Airport", "Station"], correctIndex: 2 },
        { question: "How do you say 'Please help me'?", options: ["화장실", "티켓", "호텔", "도와주세요"], correctIndex: 3 },
        { question: "What does '화장실' mean?", options: ["Ticket", "Airport", "Restaurant", "Bathroom"], correctIndex: 3 },
        { question: "Listen and choose the meaning", options: ["Airport", "Restaurant", "Bathroom", "Hotel"], correctIndex: 3, type: "listening", listenWord: "호텔" },
        { question: "Listen and choose the meaning", options: ["Help", "Bathroom", "Ticket", "Airport"], correctIndex: 2, type: "listening", listenWord: "티켓" },
      ],
    },
  ],
};
