import type { LanguageCourse } from "../types";

export const mandarinCourse: LanguageCourse = {
  language: "mandarin",
  flag: "🇨🇳",
  displayName: "Mandarin",
  lessons: [
    {
      id: "zh-greetings",
      title: "Greetings",
      description: "Learn how to greet people in Mandarin",
      words: [
        { word: "你好", translation: "Hello", pronunciation: "nǐ hǎo", example: "你好！你叫什么名字？", exampleTranslation: "Hello! What is your name?" },
        { word: "再见", translation: "Goodbye", pronunciation: "zài jiàn", example: "再见！明天见。", exampleTranslation: "Goodbye! See you tomorrow." },
        { word: "谢谢", translation: "Thank you", pronunciation: "xiè xiè", example: "谢谢你的帮助。", exampleTranslation: "Thank you for your help." },
        { word: "对不起", translation: "Sorry", pronunciation: "duì bu qǐ", example: "对不起，我迟到了。", exampleTranslation: "Sorry, I am late." },
        { word: "请", translation: "Please", pronunciation: "qǐng", example: "请坐。", exampleTranslation: "Please sit down." },
      ],
      quiz: [
        { question: "What does '你好' mean?", options: ["Goodbye", "Thank you", "Hello", "Sorry"], correctIndex: 2 },
        { question: "How do you say 'Thank you'?", options: ["请", "再见", "对不起", "谢谢"], correctIndex: 3 },
        { question: "What does '再见' mean?", options: ["Hello", "Goodbye", "Please", "Sorry"], correctIndex: 1 },
        { question: "Listen and choose the meaning", options: ["Thank you", "Hello", "Goodbye", "Please"], correctIndex: 3, type: "listening", listenWord: "请" },
        { question: "Listen and choose the meaning", options: ["Please", "Sorry", "Hello", "Goodbye"], correctIndex: 1, type: "listening", listenWord: "对不起" },
      ],
    },
    {
      id: "zh-numbers",
      title: "Numbers 1–10",
      description: "Count from one to ten in Mandarin",
      words: [
        { word: "一", translation: "One", pronunciation: "yī" },
        { word: "二", translation: "Two", pronunciation: "èr" },
        { word: "三", translation: "Three", pronunciation: "sān" },
        { word: "四", translation: "Four", pronunciation: "sì" },
        { word: "五", translation: "Five", pronunciation: "wǔ" },
        { word: "六", translation: "Six", pronunciation: "liù" },
        { word: "七", translation: "Seven", pronunciation: "qī" },
        { word: "八", translation: "Eight", pronunciation: "bā" },
        { word: "九", translation: "Nine", pronunciation: "jiǔ" },
        { word: "十", translation: "Ten", pronunciation: "shí" },
      ],
      quiz: [
        { question: "What does '三' mean?", options: ["Two", "Four", "Three", "Five"], correctIndex: 2 },
        { question: "How do you say 'Seven'?", options: ["六", "七", "八", "九"], correctIndex: 1 },
        { question: "What does '十' mean?", options: ["Eight", "Nine", "Six", "Ten"], correctIndex: 3 },
        { question: "Listen and choose the meaning", options: ["Four", "Five", "Six", "Three"], correctIndex: 1, type: "listening", listenWord: "五" },
        { question: "Listen and choose the meaning", options: ["Two", "Three", "One", "Four"], correctIndex: 2, type: "listening", listenWord: "一" },
      ],
    },
    {
      id: "zh-family",
      title: "Family",
      description: "Learn family member words in Mandarin",
      words: [
        { word: "妈妈", translation: "Mom", pronunciation: "māmā", example: "我的妈妈很漂亮。", exampleTranslation: "My mom is beautiful." },
        { word: "爸爸", translation: "Dad", pronunciation: "bàba", example: "爸爸在工作。", exampleTranslation: "Dad is working." },
        { word: "哥哥", translation: "Older brother", pronunciation: "gēgē", example: "我哥哥很高。", exampleTranslation: "My older brother is tall." },
        { word: "姐姐", translation: "Older sister", pronunciation: "jiějie", example: "姐姐在学校。", exampleTranslation: "Older sister is at school." },
        { word: "弟弟", translation: "Younger brother", pronunciation: "dìdi", example: "弟弟很可爱。", exampleTranslation: "Younger brother is cute." },
        { word: "妹妹", translation: "Younger sister", pronunciation: "mèimei", example: "妹妹喜欢唱歌。", exampleTranslation: "Younger sister likes to sing." },
      ],
      quiz: [
        { question: "What does '妈妈' mean?", options: ["Dad", "Mom", "Sister", "Brother"], correctIndex: 1 },
        { question: "How do you say 'Older brother'?", options: ["弟弟", "爸爸", "哥哥", "姐姐"], correctIndex: 2 },
        { question: "What does '妹妹' mean?", options: ["Older sister", "Mom", "Younger sister", "Dad"], correctIndex: 2 },
        { question: "Listen and choose the meaning", options: ["Younger sister", "Mom", "Younger brother", "Older sister"], correctIndex: 3, type: "listening", listenWord: "姐姐" },
        { question: "Listen and choose the meaning", options: ["Mom", "Older brother", "Dad", "Older sister"], correctIndex: 2, type: "listening", listenWord: "爸爸" },
      ],
    },
    {
      id: "zh-food",
      title: "Food & Drink",
      description: "Learn common food and drink words in Mandarin",
      words: [
        { word: "米饭", translation: "Rice", pronunciation: "mǐ fàn", example: "我想吃米饭。", exampleTranslation: "I want to eat rice." },
        { word: "水", translation: "Water", pronunciation: "shuǐ", example: "请给我一杯水。", exampleTranslation: "Please give me a glass of water." },
        { word: "茶", translation: "Tea", pronunciation: "chá", example: "我喜欢喝茶。", exampleTranslation: "I like drinking tea." },
        { word: "面条", translation: "Noodles", pronunciation: "miàn tiáo", example: "这碗面条很好吃。", exampleTranslation: "This bowl of noodles is delicious." },
        { word: "鱼", translation: "Fish", pronunciation: "yú", example: "我们今天吃鱼。", exampleTranslation: "We are eating fish today." },
        { word: "苹果", translation: "Apple", pronunciation: "píng guǒ", example: "我每天吃一个苹果。", exampleTranslation: "I eat an apple every day." },
      ],
      quiz: [
        { question: "What does '米饭' mean?", options: ["Tea", "Water", "Rice", "Fish"], correctIndex: 2 },
        { question: "How do you say 'Water'?", options: ["茶", "米饭", "水", "面条"], correctIndex: 2 },
        { question: "What does '面条' mean?", options: ["Fish", "Noodles", "Apple", "Tea"], correctIndex: 1 },
        { question: "Listen and choose the meaning", options: ["Rice", "Noodles", "Apple", "Fish"], correctIndex: 2, type: "listening", listenWord: "苹果" },
        { question: "Listen and choose the meaning", options: ["Water", "Rice", "Tea", "Apple"], correctIndex: 2, type: "listening", listenWord: "茶" },
      ],
    },
    {
      id: "zh-colors",
      title: "Colors",
      description: "Learn the basic colors in Mandarin",
      words: [
        { word: "红色", translation: "Red", pronunciation: "hóng sè", example: "这朵花是红色的。", exampleTranslation: "This flower is red." },
        { word: "蓝色", translation: "Blue", pronunciation: "lán sè", example: "天空是蓝色的。", exampleTranslation: "The sky is blue." },
        { word: "绿色", translation: "Green", pronunciation: "lǜ sè", example: "草是绿色的。", exampleTranslation: "The grass is green." },
        { word: "黄色", translation: "Yellow", pronunciation: "huáng sè", example: "香蕉是黄色的。", exampleTranslation: "Bananas are yellow." },
        { word: "黑色", translation: "Black", pronunciation: "hēi sè", example: "这只猫是黑色的。", exampleTranslation: "This cat is black." },
        { word: "白色", translation: "White", pronunciation: "bái sè", example: "雪是白色的。", exampleTranslation: "Snow is white." },
      ],
      quiz: [
        { question: "What does '红色' mean?", options: ["Blue", "Green", "Red", "Yellow"], correctIndex: 2 },
        { question: "How do you say 'Blue'?", options: ["绿色", "红色", "蓝色", "黑色"], correctIndex: 2 },
        { question: "What does '黄色' mean?", options: ["Green", "Yellow", "White", "Black"], correctIndex: 1 },
        { question: "Listen and choose the meaning", options: ["Black", "White", "Red", "Blue"], correctIndex: 1, type: "listening", listenWord: "白色" },
        { question: "Listen and choose the meaning", options: ["Blue", "Yellow", "Green", "Red"], correctIndex: 2, type: "listening", listenWord: "绿色" },
      ],
    },
    {
      id: "zh-travel",
      title: "Travel",
      description: "Essential phrases for travelling in Mandarin",
      words: [
        { word: "机场", translation: "Airport", pronunciation: "jī chǎng", example: "我们去机场。", exampleTranslation: "We are going to the airport." },
        { word: "酒店", translation: "Hotel", pronunciation: "jiǔ diàn", example: "这个酒店很舒适。", exampleTranslation: "This hotel is very comfortable." },
        { word: "餐厅", translation: "Restaurant", pronunciation: "cān tīng", example: "餐厅几点开门？", exampleTranslation: "What time does the restaurant open?" },
        { word: "帮助", translation: "Help", pronunciation: "bāng zhù", example: "我需要帮助！", exampleTranslation: "I need help!" },
        { word: "厕所", translation: "Bathroom", pronunciation: "cè suǒ", example: "厕所在哪里？", exampleTranslation: "Where is the bathroom?" },
        { word: "票", translation: "Ticket", pronunciation: "piào", example: "我要买一张票。", exampleTranslation: "I want to buy a ticket." },
      ],
      quiz: [
        { question: "What does '机场' mean?", options: ["Hotel", "Restaurant", "Airport", "Station"], correctIndex: 2 },
        { question: "How do you say 'Help'?", options: ["厕所", "票", "酒店", "帮助"], correctIndex: 3 },
        { question: "What does '厕所' mean?", options: ["Ticket", "Airport", "Restaurant", "Bathroom"], correctIndex: 3 },
        { question: "Listen and choose the meaning", options: ["Airport", "Restaurant", "Bathroom", "Hotel"], correctIndex: 3, type: "listening", listenWord: "酒店" },
        { question: "Listen and choose the meaning", options: ["Help", "Bathroom", "Ticket", "Airport"], correctIndex: 2, type: "listening", listenWord: "票" },
      ],
    },
  ],
};
