import type { LanguageCourse } from "../types";

export const spanishCourse: LanguageCourse = {
  language: "spanish",
  flag: "🇪🇸",
  displayName: "Spanish",
  lessons: [
    {
      id: "es-greetings",
      title: "Greetings",
      description: "Learn how to say hello and goodbye",
      words: [
        { word: "Hola", translation: "Hello", pronunciation: "OH-lah", example: "¡Hola! ¿Cómo estás?", exampleTranslation: "Hello! How are you?" },
        { word: "Adiós", translation: "Goodbye", pronunciation: "ah-DYOS", example: "¡Adiós! Hasta luego.", exampleTranslation: "Goodbye! See you later." },
        { word: "Buenos días", translation: "Good morning", pronunciation: "BWEH-nos DEE-as", example: "Buenos días, señor.", exampleTranslation: "Good morning, sir." },
        { word: "Buenas noches", translation: "Good night", pronunciation: "BWEH-nas NOH-ches", example: "Buenas noches, hasta mañana.", exampleTranslation: "Good night, see you tomorrow." },
        { word: "Por favor", translation: "Please", pronunciation: "por fah-BOR", example: "Un café, por favor.", exampleTranslation: "A coffee, please." },
      ],
      quiz: [
        { question: "What does 'Hola' mean?", options: ["Goodbye", "Hello", "Please", "Thank you"], correctIndex: 1 },
        { question: "How do you say 'Good morning'?", options: ["Buenas noches", "Adiós", "Buenos días", "Hola"], correctIndex: 2 },
        { question: "What does 'Por favor' mean?", options: ["Excuse me", "Thank you", "Sorry", "Please"], correctIndex: 3 },
        { question: "Listen and choose the meaning", options: ["Hello", "Good night", "Goodbye", "Good morning"], correctIndex: 2, type: "listening", listenWord: "Adiós" },
        { question: "Listen and choose the meaning", options: ["Please", "Hello", "Good night", "Goodbye"], correctIndex: 2, type: "listening", listenWord: "Buenas noches" },
      ],
    },
    {
      id: "es-numbers",
      title: "Numbers 1–10",
      description: "Count from one to ten in Spanish",
      words: [
        { word: "Uno", translation: "One", pronunciation: "OO-noh" },
        { word: "Dos", translation: "Two", pronunciation: "dohs" },
        { word: "Tres", translation: "Three", pronunciation: "trehs" },
        { word: "Cuatro", translation: "Four", pronunciation: "KWAH-troh" },
        { word: "Cinco", translation: "Five", pronunciation: "SEEN-koh" },
        { word: "Seis", translation: "Six", pronunciation: "says" },
        { word: "Siete", translation: "Seven", pronunciation: "SYEH-teh" },
        { word: "Ocho", translation: "Eight", pronunciation: "OH-choh" },
        { word: "Nueve", translation: "Nine", pronunciation: "NWEH-beh" },
        { word: "Diez", translation: "Ten", pronunciation: "dyehs" },
      ],
      quiz: [
        { question: "What does 'Tres' mean?", options: ["Two", "Four", "Three", "Five"], correctIndex: 2 },
        { question: "How do you say 'Seven'?", options: ["Seis", "Siete", "Ocho", "Nueve"], correctIndex: 1 },
        { question: "What does 'Diez' mean?", options: ["Eight", "Nine", "Six", "Ten"], correctIndex: 3 },
        { question: "Listen and choose the meaning", options: ["Four", "Five", "Six", "Three"], correctIndex: 1, type: "listening", listenWord: "Cinco" },
        { question: "Listen and choose the meaning", options: ["Two", "Three", "One", "Four"], correctIndex: 2, type: "listening", listenWord: "Uno" },
      ],
    },
    {
      id: "es-colors",
      title: "Colors",
      description: "Learn the basic colors in Spanish",
      words: [
        { word: "Rojo", translation: "Red", pronunciation: "ROH-hoh", example: "El coche es rojo.", exampleTranslation: "The car is red." },
        { word: "Azul", translation: "Blue", pronunciation: "ah-SOOL", example: "El cielo es azul.", exampleTranslation: "The sky is blue." },
        { word: "Verde", translation: "Green", pronunciation: "BEHR-deh", example: "La hierba es verde.", exampleTranslation: "The grass is green." },
        { word: "Amarillo", translation: "Yellow", pronunciation: "ah-mah-REE-yoh", example: "El sol es amarillo.", exampleTranslation: "The sun is yellow." },
        { word: "Negro", translation: "Black", pronunciation: "NEH-groh", example: "El gato es negro.", exampleTranslation: "The cat is black." },
        { word: "Blanco", translation: "White", pronunciation: "BLAHN-koh", example: "La nieve es blanca.", exampleTranslation: "The snow is white." },
      ],
      quiz: [
        { question: "What does 'Rojo' mean?", options: ["Blue", "Green", "Red", "Yellow"], correctIndex: 2 },
        { question: "How do you say 'Blue'?", options: ["Verde", "Rojo", "Azul", "Negro"], correctIndex: 2 },
        { question: "What does 'Amarillo' mean?", options: ["Green", "Yellow", "White", "Black"], correctIndex: 1 },
        { question: "Listen and choose the meaning", options: ["Black", "White", "Red", "Blue"], correctIndex: 1, type: "listening", listenWord: "Blanco" },
        { question: "Listen and choose the meaning", options: ["Blue", "Yellow", "Green", "Red"], correctIndex: 2, type: "listening", listenWord: "Verde" },
      ],
    },
    {
      id: "es-family",
      title: "Family",
      description: "Learn family member words in Spanish",
      words: [
        { word: "Madre", translation: "Mother", pronunciation: "MAH-dreh", example: "Mi madre es amable.", exampleTranslation: "My mother is kind." },
        { word: "Padre", translation: "Father", pronunciation: "PAH-dreh", example: "Mi padre trabaja mucho.", exampleTranslation: "My father works a lot." },
        { word: "Hermano", translation: "Brother", pronunciation: "ehr-MAH-noh", example: "Tengo un hermano mayor.", exampleTranslation: "I have an older brother." },
        { word: "Hermana", translation: "Sister", pronunciation: "ehr-MAH-nah", example: "Mi hermana es muy lista.", exampleTranslation: "My sister is very smart." },
        { word: "Abuelo", translation: "Grandfather", pronunciation: "ah-BWEH-loh", example: "Mi abuelo tiene ochenta años.", exampleTranslation: "My grandfather is eighty years old." },
        { word: "Abuela", translation: "Grandmother", pronunciation: "ah-BWEH-lah", example: "La abuela cocina muy bien.", exampleTranslation: "Grandmother cooks very well." },
      ],
      quiz: [
        { question: "What does 'Madre' mean?", options: ["Father", "Sister", "Mother", "Brother"], correctIndex: 2 },
        { question: "How do you say 'Brother'?", options: ["Hermana", "Padre", "Hermano", "Abuelo"], correctIndex: 2 },
        { question: "What does 'Abuelo' mean?", options: ["Grandmother", "Father", "Grandfather", "Uncle"], correctIndex: 2 },
        { question: "Listen and choose the meaning", options: ["Sister", "Mother", "Grandfather", "Grandmother"], correctIndex: 3, type: "listening", listenWord: "Abuela" },
        { question: "Listen and choose the meaning", options: ["Brother", "Father", "Sister", "Mother"], correctIndex: 1, type: "listening", listenWord: "Padre" },
      ],
    },
    {
      id: "es-food",
      title: "Food & Drink",
      description: "Learn common food and drink words in Spanish",
      words: [
        { word: "Pan", translation: "Bread", pronunciation: "pahn", example: "Quiero pan, por favor.", exampleTranslation: "I want bread, please." },
        { word: "Agua", translation: "Water", pronunciation: "AH-gwah", example: "Un vaso de agua, por favor.", exampleTranslation: "A glass of water, please." },
        { word: "Leche", translation: "Milk", pronunciation: "LEH-cheh", example: "El niño bebe leche.", exampleTranslation: "The child drinks milk." },
        { word: "Pollo", translation: "Chicken", pronunciation: "POH-yoh", example: "El pollo está delicioso.", exampleTranslation: "The chicken is delicious." },
        { word: "Arroz", translation: "Rice", pronunciation: "ah-RROS", example: "Me gusta el arroz.", exampleTranslation: "I like rice." },
        { word: "Manzana", translation: "Apple", pronunciation: "mahn-SAH-nah", example: "Como una manzana cada día.", exampleTranslation: "I eat an apple every day." },
      ],
      quiz: [
        { question: "What does 'Pan' mean?", options: ["Milk", "Water", "Bread", "Rice"], correctIndex: 2 },
        { question: "How do you say 'Water'?", options: ["Leche", "Pan", "Agua", "Arroz"], correctIndex: 2 },
        { question: "What does 'Pollo' mean?", options: ["Rice", "Bread", "Chicken", "Apple"], correctIndex: 2 },
        { question: "Listen and choose the meaning", options: ["Bread", "Chicken", "Apple", "Milk"], correctIndex: 2, type: "listening", listenWord: "Manzana" },
        { question: "Listen and choose the meaning", options: ["Water", "Rice", "Milk", "Apple"], correctIndex: 2, type: "listening", listenWord: "Leche" },
      ],
    },
    {
      id: "es-travel",
      title: "Travel",
      description: "Essential phrases for travelling in Spanish",
      words: [
        { word: "Aeropuerto", translation: "Airport", pronunciation: "ah-eh-roh-PWEHR-toh", example: "El aeropuerto está lejos.", exampleTranslation: "The airport is far." },
        { word: "Hotel", translation: "Hotel", pronunciation: "oh-TEHL", example: "Reservé una habitación en el hotel.", exampleTranslation: "I booked a room at the hotel." },
        { word: "Restaurante", translation: "Restaurant", pronunciation: "res-tow-RAHN-teh", example: "El restaurante abre a las ocho.", exampleTranslation: "The restaurant opens at eight." },
        { word: "Ayuda", translation: "Help", pronunciation: "ah-YOO-dah", example: "¡Necesito ayuda!", exampleTranslation: "I need help!" },
        { word: "Baño", translation: "Bathroom", pronunciation: "BAH-nyoh", example: "¿Dónde está el baño?", exampleTranslation: "Where is the bathroom?" },
        { word: "Billete", translation: "Ticket", pronunciation: "bee-YEH-teh", example: "Necesito un billete de tren.", exampleTranslation: "I need a train ticket." },
      ],
      quiz: [
        { question: "What does 'Aeropuerto' mean?", options: ["Hotel", "Restaurant", "Airport", "Station"], correctIndex: 2 },
        { question: "How do you say 'Help'?", options: ["Baño", "Billete", "Hotel", "Ayuda"], correctIndex: 3 },
        { question: "What does 'Baño' mean?", options: ["Ticket", "Airport", "Restaurant", "Bathroom"], correctIndex: 3 },
        { question: "Listen and choose the meaning", options: ["Airport", "Restaurant", "Bathroom", "Hotel"], correctIndex: 3, type: "listening", listenWord: "Hotel" },
        { question: "Listen and choose the meaning", options: ["Help", "Bathroom", "Ticket", "Airport"], correctIndex: 2, type: "listening", listenWord: "Billete" },
      ],
    },
  ],
};
